name : NASA project ci demo
on : 
  push :
    branches : [main]
  pull_request :
    branches : [main]
jobs : 
  build:
    runs-on : macos-latest
    steps: 
      - uses : actions/checkout@v1
      - name : Use node.js version 16
        uses : actions/setup-node@v1
        with :
          node-version : '16'
      - run :  npm install --prefix server
      - run :  npm test